[server]
Debug=true
Mode = "release"
Port = 8777
DefaultReadTimeOut = 10
DefaultWriteTimeOut = 10
DefaultMaxHeaderBytes = 20
AccessLog = "logs/access.log"


[db]
# 驱动类型，目前只支持sqlite
Driver = "sqlite3" 
# 生成的数据库文件地址，默认在/data目录
DB = "data/20190403.db"
